"""adiciona estrutura de SLA

Revision ID: 47aab615c0bc
Revises: c9e1cb19f02b
Create Date: 2026-09-25 18:54:46.038658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47aab615c0bc'
down_revision: Union[str, Sequence[str], None] = 'c9e1cb19f02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicas_sla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('primeiro_atendimento_minutos', sa.Integer(), nullable=False),
    sa.Column('resolucao_minutos', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prioridade')
    )
    op.add_column('chamados', sa.Column('primeiro_atendimento_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chamados', sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chamados', sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True))

    op.bulk_insert(
        sa.table(
            'politicas_sla',
            sa.column('prioridade', sa.String()),
            sa.column('primeiro_atendimento_minutos', sa.Integer()),
            sa.column('resolucao_minutos', sa.Integer()),
            sa.column('ativo', sa.Boolean()),
        ),
        [
            {
                'prioridade': 'baixa',
                'primeiro_atendimento_minutos': 480,
                'resolucao_minutos': 2400,
                'ativo': True,
            },
            {
                'prioridade': 'normal',
                'primeiro_atendimento_minutos': 240,
                'resolucao_minutos': 1440,
                'ativo': True,
            },
            {
                'prioridade': 'alta',
                'primeiro_atendimento_minutos': 120,
                'resolucao_minutos': 480,
                'ativo': True,
            },
            {
                'prioridade': 'urgente',
                'primeiro_atendimento_minutos': 30,
                'resolucao_minutos': 240,
                'ativo': True,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamados', 'fechado_em')
    op.drop_column('chamados', 'resolvido_em')
    op.drop_column('chamados', 'primeiro_atendimento_em')
    op.drop_table('politicas_sla')
    # ### end Alembic commands ###
