"""adiciona calendario de SLA

Revision ID: 6938b2f99801
Revises: 47aab615c0bc
Create Date: 2026-09-25 19:44:06.831147

"""
from datetime import time
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6938b2f99801'
down_revision: Union[str, Sequence[str], None] = '47aab615c0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_sla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('segunda', sa.Boolean(), nullable=False),
    sa.Column('terca', sa.Boolean(), nullable=False),
    sa.Column('quarta', sa.Boolean(), nullable=False),
    sa.Column('quinta', sa.Boolean(), nullable=False),
    sa.Column('sexta', sa.Boolean(), nullable=False),
    sa.Column('sabado', sa.Boolean(), nullable=False),
    sa.Column('domingo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )

    configuracao_sla = sa.table(
        "configuracao_sla",
        sa.column("timezone", sa.String),
        sa.column("hora_inicio", sa.Time),
        sa.column("hora_fim", sa.Time),
        sa.column("segunda", sa.Boolean),
        sa.column("terca", sa.Boolean),
        sa.column("quarta", sa.Boolean),
        sa.column("quinta", sa.Boolean),
        sa.column("sexta", sa.Boolean),
        sa.column("sabado", sa.Boolean),
        sa.column("domingo", sa.Boolean),
    )

    op.bulk_insert(
        configuracao_sla,
        [
            {
                "timezone": "America/Sao_Paulo",
                "hora_inicio": time(8, 0),
                "hora_fim": time(18, 0),
                "segunda": True,
                "terca": True,
                "quarta": True,
                "quinta": True,
                "sexta": True,
                "sabado": False,
                "domingo": False,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feriados')
    op.drop_table('configuracao_sla')
    # ### end Alembic commands ###
