"""torna categoria obrigatoria nos chamados

Revision ID: 71a163b8e61c
Revises: 1470a5cd81d9
Create Date: 2026-09-24 22:09:23.732786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a163b8e61c'
down_revision: Union[str, Sequence[str], None] = '1470a5cd81d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamados', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chamados', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
