"""remove categoria textual dos chamados

Revision ID: c9e1cb19f02b
Revises: 71a163b8e61c
Create Date: 2026-09-25 14:58:58.819696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e1cb19f02b'
down_revision: Union[str, Sequence[str], None] = '71a163b8e61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamados', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restaura a coluna textual de categoria."""

    # Recria primeiro permitindo NULL para os chamados existentes.
    op.add_column(
        "chamados",
        sa.Column(
            "categoria",
            sa.VARCHAR(length=50),
            nullable=True,
        ),
    )

    # Reconstrói o valor textual usando a FK categoria_id.
    op.execute(
        sa.text(
            """
            UPDATE chamados AS c
            SET categoria = cat.nome
            FROM categorias AS cat
            WHERE c.categoria_id = cat.id
            """
        )
    )

    # Restaura a restrição original.
    op.alter_column(
        "chamados",
        "categoria",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
